### ISSUE TITLE
Thrift isn't giving you as much type safety as protocol buffers

### ISSUE THREAD

**Issue by wtanaka** [amvtek/PySerializers#3]
I've been looking into the tradeoffs between a few IDL-enabled serializes for Python, and it seems like the thrift Python code generator has very little in the way of type safety.

http://wtanaka.com/node/8174

comparing the performance of

**Comment by wtanaka** [comment]
...the thrift Python and protobuf Python implementations may not be comparing apples to apples

**Comment by amvtek** [comment]
Hello,
I have read your post.
Do you have some code that better illustrate the differences you mention.
Best,
Marc

**Comment by wtanaka** [comment]
Yep, you can click the links at the top of the table headings in http://wtanaka.com/node/8174 to see the code I ran.

**Comment by amvtek** [comment]
OK, I briefly come back on this one.

First it looks to me that you are comparing thrift 0.9.2 python C extension (default normally) module to pure python protocol buffer (default also, i don't see the environment variables that would activate the C++ extension being defined). I am not sure that the thrift fastbinary C extension is involved during validation but it may. In code we have, the thrift fastbinary is what allow the library to perform fast, but we have observed that it is more liberal regarding typing (eg text are not converted to unicode) than the pure python implementation.

As for the validation failures you are observing, I think you shall fill a bug report with the thrift project. 

On our side, we are heavy users of both protocol buffers & thrift. We maintain this benchmark as we have had lot of performance & stability problems with python protocol buffers. Things are terrible with protobuf 2.5.0 you are using (segmentation faults when using C++ extension & poor performance with pure python modules). Things have improved with protobuf 2.6.1, but it is still meaningfully slower than  thrift.
