### ISSUE TITLE
What is pyext?

### ISSUE THREAD

**Issue by anentropic** [amvtek/PySerializers#4]
I noticed that `thrift/pyext` did much better than `thrift/py`  ...what is `thrift/pyext`?

**Comment by anentropic** [comment]
Is it this: https://github.com/google/protobuf/tree/master/python#c-implementation ?

i.e. ensure you have the C++ protobuf runtime library?

**Comment by amvtek** [comment]
Hello,
the benchmark differentiates in between running a certain serialization (eg thrift or protobuf)
 * with pure python implementation (serialization/py...)
 * with c extension implementation  (serialization/pyext)

As for your second remark, you are correct. What google describes is what to do to use the c extension alternative. In the context of this benchmark this would be selected by protobuf/pyext.
